import os

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")

SPREADSHEET_ID = os.environ.get("SPREADSHEET_ID")
GOOGLE_SERVICE_ACCOUNT_EMAIL = os.environ.get("GOOGLE_SERVICE_ACCOUNT_EMAIL")
GOOGLE_PRIVATE_KEY = os.environ.get("GOOGLE_PRIVATE_KEY")

FACT_SHEET_NAME = "fact"
SYSTEM_SHEET_NAME = "system"

CARD1_CELL = "K2"
CARD2_CELL = "L2"
DEFAULT_CURRENCY = "UZS"